/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrabalhoIndexRouteImport } from './routes/trabalho/index'
import { Route as AulasIndexRouteImport } from './routes/aulas/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhoIndexRoute = TrabalhoIndexRouteImport.update({
  id: '/trabalho/',
  path: '/trabalho/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasIndexRoute = AulasIndexRouteImport.update({
  id: '/aulas/',
  path: '/aulas/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasIndexRoute
  '/trabalho': typeof TrabalhoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasIndexRoute
  '/trabalho': typeof TrabalhoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas/': typeof AulasIndexRoute
  '/trabalho/': typeof TrabalhoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aulas' | '/trabalho'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aulas' | '/trabalho'
  id: '__root__' | '/' | '/aulas/' | '/trabalho/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasIndexRoute: typeof AulasIndexRoute
  TrabalhoIndexRoute: typeof TrabalhoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalho/': {
      id: '/trabalho/'
      path: '/trabalho'
      fullPath: '/trabalho'
      preLoaderRoute: typeof TrabalhoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas/': {
      id: '/aulas/'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasIndexRoute: AulasIndexRoute,
  TrabalhoIndexRoute: TrabalhoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
